config/routes.rb
Rails.application.routes.draw do

resources :jobs do
  member do
    post 'add_tag'
  end
end

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
	validates :title, :description, presence: true
	has_many :tags, dependent: :destroy
	accepts_nested_attributes_for :tags
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	belongs_to :job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
  	@jobs = Job.all
  end

  def new
  	@job = Job.new
  end

  def create
  	Job.create(job_params)
  	redirect_to jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    @job.update_attributes(job_params)
    redirect_to job_path
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  def show
    @job = Job.find(params[:id])
  end 

  private

  def job_params
  	params.require(:job).permit(:title, :description, :contact, :comment, tags_attributes: [:content])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
	<div>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label :description %>
		<%= f.text_area :description, size: '60x6' %>
	</div>
	<div>
		<%= f.label :contact %>
		<%= f.text_field :contact %>
	</div>
	<div>
		<%= f.label :comment %>
		<%= f.text_area :comment, size: '60x6' %>
	</div>	

<%-# need to figure out how to create tag form within the job form-%>	
<%-# tag model needs its own controller most likely-%>	
	
	<%= f.fields_for @job.tags.create do |addy_form| %>
		<%= addy_form.label :tag %>
		<%= addy_form.text_field :content%>

	<% end %>
		
	


	<div>
	<%= f.submit %>
	</div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit Posting</h1>
<%= render "form" %>

app/views/jobs/index.html.erb
<h1>RailsBridgeCorp Open Jobs</h1>

<table id="jobs">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Contact</th>
      <th>Link</th>
    </tr>
  </thead>

  <tbody>
	<% @jobs.each do |job| %>
	  <tr>
		<td><%= job.title %></td>
		<td><%= job.description %></td>
		<td><%= job.contact %></td>
		<td><%= link_to 'Show Posting', job_path(job) %></td>
	  </tr>
	<% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1>Add a job</h1>
<%= render "form" %>

app/views/jobs/show.html.erb
	
	<h1><%= @job.title %></h1>
	<p>Description: <%= @job.description %></p>
	<p>Contact: <%= @job.contact %></p>
	<p>Comment: <%= @job.comment %></p>
	<h5><%= link_to 'Edit Posting', edit_job_path %></h5>
	<h5><%= link_to 'Delete Posting', @job, method: :Delete %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="left-nav">
    <ul>
      <li><%= link_to "Home", jobs_path %></li>
    </ul>
  </div>
  <div class="right-nav">
    <ul>
      <li><%= link_to "Add Job", new_job_path %></li>
    </ul>
  </div>
  <div class="clearfix"></div>
</header>

  <%= yield %>

</body>
</html>